### PR TITLE
bring device_grid to feature parity with grid

### PR DESCRIPTION
**Pull request by ViRu-ThE-ViRuS**

### CODE REVIEW

**Comment by yuzhoumo** [comment]
```
OpenCL build log:
<program source>:90:7: warning: no previous prototype for function 'get_stable_state_b'
float get_stable_state_b(const float total_mass) {
      ^
<program source>:106:14: warning: unused variable 'size'
  const uint size = get_global_size(0); // full grid size (rows)
             ^
<program source>:139:14: warning: unused variable 'width'
  const uint width = dims[0];
             ^
<program source>:160:36: warning: comparison of unsigned expression >= 0 is always true
  const bool top_valid = (row - 1) >= 0;
                         ~~~~~~~~~ ^  ~
<program source>:265:14: error: call to '__cl_fmax' is ambiguous
      flow = FCLAMP(flow, 0, fmin(max_speed, remaining_mass));
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<program source>:26:26: note: expanded from macro 'FCLAMP'
#define FCLAMP(x, l, h) (fmax(l, fmin(x, h)))
                         ^~~~~~~~~~~~~~~~~~~
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:4549:28: note: expanded from macro 'fmax'
    #define fmax(__x, __y) __cl_fmax(__x, __y)
                           ^~~~~~~~~
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:4545:15: note: candidate function
__CLFN_FD_2FD(__cl_fmax);
              ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:1009:48: note: expanded from macro '__CLFN_FD_2FD'
#define __CLFN_FD_2FD(name) float __OVERLOAD__ name(float x, float y); \
                                               ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:4546:19: note: candidate function
__CLFN_FD_2FD_EXT(__cl_fmax);
                  ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:1079:53: note: expanded from macro '__CLFN_FD_2FD_EXT'
#define __CLFN_FD_2FD_EXT(name) float2 __OVERLOAD__ name(float2 x, float y); \
                                                    ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:4546:19: note: candidate function
__CLFN_FD_2FD_EXT(__cl_fmax);
                  ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:1080:21: note: expanded from macro '__CLFN_FD_2FD_EXT'
float3 __OVERLOAD__ name(float3 x, float y); \
                    ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:4546:19: note: candidate function
__CLFN_FD_2FD_EXT(__cl_fmax);
                  ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:1081:21: note: expanded from macro '__CLFN_FD_2FD_EXT'
float4 __OVERLOAD__ name(float4 x, float y); \
                    ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:4546:19: note: candidate function
__CLFN_FD_2FD_EXT(__cl_fmax);
                  ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:1082:21: note: expanded from macro '__CLFN_FD_2FD_EXT'
float8 __OVERLOAD__ name(float8 x, float y); \
                    ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:4546:19: note: candidate function
__CLFN_FD_2FD_EXT(__cl_fmax);
                  ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:1083:22: note: expanded from macro '__CLFN_FD_2FD_EXT'
float16 __OVERLOAD__ name(float16 x, float y);
                     ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:4545:15: note: candidate function
__CLFN_FD_2FD(__cl_fmax);
              ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:1010:21: note: expanded from macro '__CLFN_FD_2FD'
float2 __OVERLOAD__ name(float2 x, float2 y); \
                    ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:4545:15: note: candidate function
__CLFN_FD_2FD(__cl_fmax);
              ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:1011:21: note: expanded from macro '__CLFN_FD_2FD'
float3 __OVERLOAD__ name(float3 x, float3 y); \
                    ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:4545:15: note: candidate function
__CLFN_FD_2FD(__cl_fmax);
              ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:1012:21: note: expanded from macro '__CLFN_FD_2FD'
float4 __OVERLOAD__ name(float4 x, float4 y); \
                    ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:4545:15: note: candidate function
__CLFN_FD_2FD(__cl_fmax);
              ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:1013:21: note: expanded from macro '__CLFN_FD_2FD'
float8 __OVERLOAD__ name(float8 x, float8 y); \
                    ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:4545:15: note: candidate function
__CLFN_FD_2FD(__cl_fmax);
              ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:1014:22: note: expanded from macro '__CLFN_FD_2FD'
float16 __OVERLOAD__ name(float16 x, float16 y);
                     ^
<program source>:358:14: error: call to '__cl_fmax' is ambiguous
      flow = FCLAMP(flow, 0, fmin(max_speed, remaining_mass));
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<program source>:26:26: note: expanded from macro 'FCLAMP'
#define FCLAMP(x, l, h) (fmax(l, fmin(x, h)))
                         ^~~~~~~~~~~~~~~~~~~
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:4549:28: note: expanded from macro 'fmax'
    #define fmax(__x, __y) __cl_fmax(__x, __y)
                           ^~~~~~~~~
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:4545:15: note: candidate function
__CLFN_FD_2FD(__cl_fmax);
              ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:1009:48: note: expanded from macro '__CLFN_FD_2FD'
#define __CLFN_FD_2FD(name) float __OVERLOAD__ name(float x, float y); \
                                               ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:4546:19: note: candidate function
__CLFN_FD_2FD_EXT(__cl_fmax);
                  ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:1079:53: note: expanded from macro '__CLFN_FD_2FD_EXT'
#define __CLFN_FD_2FD_EXT(name) float2 __OVERLOAD__ name(float2 x, float y); \
                                                    ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:4546:19: note: candidate function
__CLFN_FD_2FD_EXT(__cl_fmax);
                  ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:1080:21: note: expanded from macro '__CLFN_FD_2FD_EXT'
float3 __OVERLOAD__ name(float3 x, float y); \
                    ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:4546:19: note: candidate function
__CLFN_FD_2FD_EXT(__cl_fmax);
                  ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:1081:21: note: expanded from macro '__CLFN_FD_2FD_EXT'
float4 __OVERLOAD__ name(float4 x, float y); \
                    ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:4546:19: note: candidate function
__CLFN_FD_2FD_EXT(__cl_fmax);
                  ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:1082:21: note: expanded from macro '__CLFN_FD_2FD_EXT'
float8 __OVERLOAD__ name(float8 x, float y); \
                    ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:4546:19: note: candidate function
__CLFN_FD_2FD_EXT(__cl_fmax);
                  ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:1083:22: note: expanded from macro '__CLFN_FD_2FD_EXT'
float16 __OVERLOAD__ name(float16 x, float y);
                     ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:4545:15: note: candidate function
__CLFN_FD_2FD(__cl_fmax);
              ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:1010:21: note: expanded from macro '__CLFN_FD_2FD'
float2 __OVERLOAD__ name(float2 x, float2 y); \
                    ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:4545:15: note: candidate function
__CLFN_FD_2FD(__cl_fmax);
              ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:1011:21: note: expanded from macro '__CLFN_FD_2FD'
float3 __OVERLOAD__ name(float3 x, float3 y); \
                    ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:4545:15: note: candidate function
__CLFN_FD_2FD(__cl_fmax);
              ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:1012:21: note: expanded from macro '__CLFN_FD_2FD'
float4 __OVERLOAD__ name(float4 x, float4 y); \
                    ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:4545:15: note: candidate function
__CLFN_FD_2FD(__cl_fmax);
              ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:1013:21: note: expanded from macro '__CLFN_FD_2FD'
float8 __OVERLOAD__ name(float8 x, float8 y); \
                    ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:4545:15: note: candidate function
__CLFN_FD_2FD(__cl_fmax);
              ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:1014:22: note: expanded from macro '__CLFN_FD_2FD'
float16 __OVERLOAD__ name(float16 x, float16 y);
                     ^
<program source>:297:20: warning: comparison of integers of different signs: 'int' and 'uint' (aka 'unsigned int')
      for (; right <= min(col + horizontal_reach, width - 1); right += 1) {
             ~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

compute shader compile error, investigating

**Comment by yuzhoumo** [comment]
added build log print and thread count sanity check

**Comment by yuzhoumo** [comment]
```
#define FCLAMP(x, l, h) (fmax(l, fmin(x, h)))
```
fmax function is overloaded in OpenCL to handle different data types (float, float2, float3, float4, etc) and compiler can't determine which overload to choose for the FCLAMP macro

explicitly cast to float:
```
#define FCLAMP(x, l, h) (fmax((float)l, fmin((float)x, (float)h)))
```

**Comment by yuzhoumo** [comment]
pushed fix

**Comment by ViRu-ThE-ViRuS** [comment]
water works well enough, device grid supports all features that cpu grid does (though implementations are missing)

**Pull request merged**
